### ISSUE TITLE
iplug options: add folder option

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#125]
Let’s say there is a cmd like this:

```vim
iplug add -f completion https://github.com/preservim/nerdcommenter
``` 

it add nerdcommenter under

```vim
~/.vim/pack/completion/start/
``` 

with multi options

```vim

iplug add -f completion -t opt https://github.com/preservim/nerdcommenter
``` 

it add nerdcommenter under

```vim
~/.vim/pack/completion/opt/
```

**Comment by terrychou** [comment]
`iplug` will puts vim 8 packages (which has sub-directory `start` or `opt`) under `~/.vim/pack/`; puts plugins (which is not a package) under `~/.vim/pack/ivim/start` or `~/.vim/pack/ivim/opt`, for better management. A `folder` option seems not necessary since iVim tries to abstract this structure from users.

**Comment by suliveevil** [comment]
Yeah,I rethought about it, classify by folder may not be a good idea.
I wlll recognize my rc files instead.
