### ISSUE TITLE
Why not Vim 8?

### ISSUE THREAD

**Issue by sedm0784** [terrychou/iVim#14]
This is not a problem for me&thinsp;&mdash;&thinsp;I'm actually still running Vim 7.4 on all my computers&thinsp;&mdash;&thinsp;I'm just curious: why is iVim Vim 7 and not Vim 8?

**Comment by terrychou** [comment]
I have been considering this. Since I have been trying best to make iVim's own code interfere with vim's as least as possible, it would not be a difficult thing to do. However, it would be sort of "trivial". There would be many little aspects you have to take into account: modified parts, differences between vim 7 and 8, testing etc. Therefore, I don't see it has high priority right now.

**Comment by mvolkmann** [comment]
I hope you are able to base iVim on Vim 8 at some point. The main feature in my opinion is support for asynchronous I/O which makes automatic linting of code much faster. Of course that is of little use if it’s not possible to use plugins with iVim. Is it a goal to enable use of plugins like ALE?

**Comment by drbarrett** [comment]
Pure vimscript plugins work and can be loaded with pathogen. Since ALE requires external apps to do the linting there’s no way they'll work here since ivim can’t run other programs.

I assume that holzschu’s fork would work with python based plugins but I haven’t tried to build his version yet.

**Comment by terrychou** [comment]
Finally, iVim upgrades to version 2, which has the vim core 8.1.
