### ISSUE TITLE
z.lua 内置到 iVim 里

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#140]
[z.lua](https://github.com/skywind3000/z.lua) 是由 skywind3000 开发的一个自包含的 lua 脚本。
能不能把它内置到 iVim 里作为 z 命令使用啊？

**Comment by terrychou** [comment]
Rather than a pure lua script, z.lua seems to utilize shell scripts (from different famous shells, like bash, fish ...) and environment variables to work. Unfortunately these are not well supported in `ivish`.

PS. please use English to discuss here. I have no problems understanding Chinese, but people who don't know it may miss the chance to help.

**Comment by suliveevil** [comment]
Dependencies is always a problem due to Apple’s restrictions.
I will find a replacement using pure vimscript.

😂 I will Switch this issue to English.
