### ISSUE TITLE
【iexdir】autodetect whether a symlink is deleted and automatic remove from list

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#164]
This will combine the delete outside iVim and inside.

**Comment by terrychou** [comment]
Instead of detecting the deletion automatically, I made it like this:
1. `:iexdir-list` will mark the links with problems with a `-` after their indices;
2. the new subcommand `:iexdir-fix` tries to fix possible problems for them.

This is included in version 2.23(3) in TestFlight, please give it a try.

**Comment by suliveevil** [comment]
I will try that soon.

**Comment by suliveevil** [comment]
This is awesome! `iexdir` now can run `iexdir add -o _exdir/PolyGit` as expected.
I tried iexdir fix too, this is exactly what I need.

**Comment by suliveevil** [comment]
![iexdir add](https://user-images.githubusercontent.com/35763237/86591709-a4f16480-bfc4-11ea-8fce-82746c9fbf0d.png)

![iexdir fix](https://user-images.githubusercontent.com/35763237/86591728-b175bd00-bfc4-11ea-9fd1-7aef574d5472.png)
