### ISSUE TITLE
unable to add fonts

### ISSUE THREAD

**Issue by mtwebb** [terrychou/iVim#171]
Hi Terry,
I tried adding a font in both on iPadOS 14 beta six and iOS 13. Both places saw this error:

![IMG_1219](https://user-images.githubusercontent.com/1376680/92345929-08107d80-f080-11ea-9a85-0b3ef533a9fd.jpeg)
![IMG_1220](https://user-images.githubusercontent.com/1376680/92345933-0f378b80-f080-11ea-8146-fa0ff5375585.jpeg)
here are the fonts I tried:
https://fonts.google.com/specimen/Source+Code+Pro
https://www.janfromm.de/typefaces/camingomono/camingocode/

My goal is to get bold and italic fonts working in ivim. I saw that source code pro is included in ivim, but I see only mention of the regular variant in the ifont list. 

Cheers for iVim. I use it daily.   Put iplug to work today and it worked great.

**Comment by terrychou** [comment]
According to the screenshots, you invoked the "Share with iVim" item in the system's share sheet. Instead of that, you need the "Copy to iVim" one to install fonts. Please refer to issue #76.

`iVim` includes the bold and italic versions of `Source Code Pro` by default. Choosing the regular item makes the bold and italic ones ready. They will show at the proper situations.

**Comment by mtwebb** [comment]
Ahh, how did I miss that issue? Thanks Terry, opening with idoc works great. Good to know about the italic version  of source code pro is included.
