### ISSUE TITLE
Open In iVim Action is missing in iOS 14

### ISSUE THREAD

**Issue by ahayman** [terrychou/iVim#172]
With my normal workflow, I find the file I want to edit in Files, tap on Share, then select "Open in iVim". I found that if I "favorited" the "Open in iVim" action, I could simply tap on the file to open it in iVim.  This was very convenient.

That option disappeared when I updated to iOS 14. The only thing I can do is select `iVim` and "share" the contents, which copies the the text into iVim in a new buffer instead of allowing me to edit the file in place. 

I can use `:idoc` to edit files in place, so at least iVim is still usable. But I much prefered the `Open in iVim` option. It make switching files a lot easier.

**Comment by mchalkley** [comment]
I've had the same problem, and it's a real source of frustration.  Try this:  In the application you're trying to use "Open in..." from, open the Share sheet, then tap-hold on iVim & see if you get multiple options, one of which is "Open in...", and will allow the previous functionality.

It works for me in Notebooks, and I bring that up because I can't take credit for discovering this insanely non-intuitive "improvement" in iOS/iPadOS.  Alfons Schmid, the author of Notebooks (notebooksapp.com), figured it out in response to a support request I submitted to him.  Notebooks is an awesome Markdown editor, notebook app, & multi-purpose repository.

Hope it works for you as well as it does for me!

Mark

**Comment by ahayman** [comment]
The recent update (about a week ago) seems to have fixed this problem.  Thank you!  It really makes my workflow so much easier when I can open a file in the Files app directly in iVim.  It’s truly awesome.
