### ISSUE TITLE
Still floundering with syncing between ivim and vim

### ISSUE THREAD

**Issue by EricEWeir** [terrychou/iVim#233]
I've put a copy of my vimwiki directory in iCloud Drive. When I open the index.wiki file, which provides hyperlinks to other files in the directory highlighting of links is lost whether the file is opened via ivim or vim. 

If anyone has thoughts about why this occurs and what I can do to get highlighting back it would be appreciated.

Thanks.

**Comment by EricEWeir** [comment]
I switched to `wiki.vim`. With help from its developer I’m now getting link highlighting and folding wherever files are opened, including in the cloud.

**Comment by GregoryShields** [comment]
I too have switched to wiki.vim and its creator, Karl, has been very helpful.

FWIW, the way I sync my wiki across devices, including on iPad, is through a Git repo I have hosted on a NAS drive on my local network. On iPad in particular, I use the Git client called Working Copy to push/pull changes.

I do realize that people do this in a number of different ways, but I like the way I'm doing it because I'm not relying on any third party service, especially any kind of cloud service. I'm under no delusions that my private wiki is totally secure from prying eyes, but literally uploading it to someone else's computer just doesn't seem like a good idea to me. Don't get me wrong; I'm not criticizing those who choose to do that.

Anyway, should you choose to explore this avenue, I'd be happy to help you with technical hurdles involved therewith.

**Comment by EricEWeir** [comment]
Karl was EXTREMELY helpful. Spent a lot of time with me. Got me over obstacles that I'd never have gotten over by myself. 

I'm not quite ready at the moment, but I've heard about noncoding writers who upload their stuff to Git. I've been curious about it, more for keeping a record of successive versions of a project than for syncing between devices. I might want help down the road. At least hearing about others' experiences.

So thanks, and maybe later.
