### ISSUE TITLE
Themes possible with :iplug?

### ISSUE THREAD

**Issue by bencodes07** [terrychou/iVim#257]
Hello,

I was planning to get the plugin manager but I have one question before I do so. Is it possible to install themes? The theme I am wanting to install is NeoSolarized. 

Thanks in advance!

P.S.: Do nvim plugins also work with :iplug?

**Comment by terrychou** [comment]
Yes, the plugins manager `iplug` also supports installing color schemes like other plugins. See ":help :iplug" for some details and examples.

As to nvim plugins, it depends. A plugin may probably work if iVim meets its requirements (due to limitations in iVim, even not all vim plugins work, e.g. it may need a third-party tool installed). However, if the plugin requires certain feature that is only available in nvim, then it may not work.

**Comment by bencodes07** [comment]
Thanks mate that helps! Have a good one
