### ISSUE TITLE
Using shift-space in key mapping

### ISSUE THREAD

**Issue by mchalkley** [terrychou/iVim#38]
For many years, I have mapped ‘s-space’ to PageUp, but I can’t seem to get any combination of lower and upper case lettering to work in iVim.  I can get ‘space’ to map to PageDown just fine, though.  What’s the magic combination in iVim?

(And thanks again for helping me through some basics a few days ago - iVim is absolutely AWESOME on the iPad!)

**Comment by terrychou** [comment]
I am sorry but I don't quite understand your problem here. What do you mean by "combination of lower and upper case lettering" and "the magic combination in iVim"? Examples would be appreciated.

**Comment by mchalkley** [comment]
In Vim on Windows, I currently have ‘s-space’ mapped to ‘PageUp’, but this doesn’t seem to work in iVim.  I have tried ‘s-space’ and ‘S-space’, as well as ‘s-Space’ and ‘S-Space’, but none of those variants in capitalization work.  Mapping ‘space’ to ‘PageDown’ works, so it seems to be the use of the shift key in the mapping that’s the problem.

**Comment by terrychou** [comment]
The fact that `Shift + Space` key combination does not work is because iVim does not handle it. (You can refer to ":help ios-external-keyboard" for related info.)

It is designed so on purpose because a combination of the `space` key with certain modifier key is usually reserved for iOS system use. For example, `command + space` is for invoking spotlight search; `ctrl + space` is for keyboard language switching.

A workaround would be use another key combination for your mapping.

**Comment by mchalkley** [comment]
Thanks for the clarification.
