### ISSUE TITLE
General stability

### ISSUE THREAD

**Issue by idvorkin** [terrychou/iVim#58]
I love the idea of iVim, but it’s pretty unstable for me on iPad with iOS 12. It’s frequently crashing and freezing.  

Is this happening for others? And if not, how can I help debug?

**Comment by terrychou** [comment]
The unstableness in iOS 12 is mainly caused by a drawing bug as discussed in issue #56 .

It is solved but still under testing, therefore not uploaded to the App Store yet.
If you can compile and install it via Xcode, you can check out the branch https://github.com/terrychou/iVim/tree/copyrectfix and help test it (that would be great:)).

**Comment by mtwebb** [comment]
To follow up on this, the latest published version with the above fix works great.  This issue can be closed.
