### ISSUE TITLE
Caps to Control remap not working with external keyboard

### ISSUE THREAD

**Issue by idvorkin** [terrychou/iVim#64]
Caps to control mapping is set in settings, but caps is not being remapped. Once i saw a message saying something like “Caps mapping is disabled”, but I didn’t think to write it down, and haven’t seen it since (Possibly since the soft keyboard is also comesing up (possibly related)?)

How can I help debug?

**Comment by idvorkin** [comment]
Has this been fixed? I'm still having the same issue as of 5/24/2019

**Comment by kkk669** [comment]
@idvorkin I have no issues with the default software keyboards, but when using the third-party keyboard like GBoard, caps to control mapping doesn't work as you said.

**Comment by idvorkin** [comment]
That makes sense. So should this be left open? I know the blink shell supports this correctly.

**Comment by idvorkin** [comment]
Something like: https://github.com/blinksh/blink/blob/242dbec6de46b255baa5eef9b867435bcb5a1693/Blink/TermInput.m#L440

**Comment by terrychou** [comment]
As explained in ":h ios-external-keyboard", the caps lock mapping function only works properly when the keyboard language is set to the default English one. Otherwise it will be disabled by default.

The "[caps lock] mapping DISABLED" message you mentioned was exact a sign saying that iVim may detect your keyboard setting did not meet the requirement. So it disabled the mapping.

This implementation depends on the API limitation very much. Therefore, it would be "fragile" and "picky" to work. A third-party keyboard, like GBoard, may make it stop working.

**Comment by idvorkin** [comment]
*(ps - I'm not trying to be annoying, I just love iVim, and getting Caps-> Control is the missing piece)*

     Note that due to the API limitation, only English keyboards are supported and
     will be disabled otherwise; after mapped, the default alt extended symbol 
     input will be ignored; for an alternative to extended symbol input, you may
     refer to digraph; however, the alt mapping mentioned in c. will still work 
     if enabled.        

What does it mean for the keyboard to be English?  

I'm not sure if it's relevant/helpful, but my external keyboard works with Blink and has been very stable.

**Comment by terrychou** [comment]
The "keyboard" mentioned here is the one you choose in the iOS system settings (usually at General > Keyboards, I think). It needs to be a "English" one (you can add multiple keyboards there) for the mapping to work due to the implementation. In another word, if you set yours to another language or a third-party one in iVim, iVim will detect that and disable the mapping automatically (because the input would malfunction otherwise.)

It has nothing to do with your own hardware keyboard, as long as you can connect it to your device.
