### ISSUE TITLE
[Problem/Bug] Taking over .zip extensions in native Files app

### ISSUE THREAD

**Issue by qqquwu** [terrychou/iVim#70]
When click on a .zip file in native Files app, when I uninstall iVim, the .zip file opens in an app that is able to extract it (Readdle Documents, for example).  However, with iVim installed, .zip opens in iVim.  

How to unassociate iVim with .zip files?

Thanks

**Comment by terrychou** [comment]
The Files app seems to set the default opener app for a file type according to the installation order: the latest installed wins.

Since iVim is designed to be able to open as many file types as possible, it would often become the default opener of one file type in Files app.

So installing the expected default opener app after iVim may be one solution.

**Comment by qqquwu** [comment]
Shouldn’t the solution to disable opening .zip in iVim?
