### ISSUE TITLE
Version 8.1.2110 not working

### ISSUE THREAD

**Issue by AmaruCoder** [terrychou/iVim#87]
I have upgraded to version 8.1.2110 but iVim doesn't work on iOS 13.3. It opens and remains  on a black screen until it crushes.

**Comment by terrychou** [comment]
Please provide more details: 
1) version of iVim
2) model of your device
3) from which version you did this upgrade
4) did you upgrade your iOS first or iVim
5) have you tried to reinstall
6) do you have any plugins installed

**Comment by AmaruCoder** [comment]
Thank you for the prompt reply:
1. version of iVim is 8.1.2110 (2.10)
2. iPadPro (10.5 inch)
3. I upgraded from the previous version (2.0)
4. I upgraded iOS and then iVim 
5. Reinstall doesn't work
6. I have all the plugins I use on my desktop. The ones supported, worked fine on the iPad in the previous version of iVim (2.0). I have discovered that when I have pathogen activated with:

    set nocp
    source ~/.vim/autoload/pathogen.vim
    call pathogen#infect()

The enclosed plugin prevent iVim from starting, even though (as I mentioned above) it just worked fine in the previous version of iVim.

[aColor-ios.vim.zip](https://github.com/terrychou/iVim/files/4047715/aColor-ios.vim.zip)

I have also discovered that iVim 2.10 doesn't hangs on `:q` when the following options are present on my `.vimrc` (even though it worked fine in iVim 2.00): 

    augroup Closing
        autocmd!
        au VimLeave * exe 'silent !rm ~/.vim/view/*' 
    augroup END

Thank you very much for your help.

**Comment by AmaruCoder** [comment]
It seems that the following lines (from `iColor-ios.vim`) create the problem:

    if has('mac')
        if system("osascript -e 'tell application \"Finder\" to get bounds of window of desktop' | cut -d ' ' -f 4") > 1100
            let g:aColorExternal = 1
        endif
    endif

I replaced that for:

    if has('mac') && !has('ios')
        if system("osascript -e 'tell application \"Finder\" to get bounds of window of desktop' | cut -d ' ' -f 4") > 1100
            let g:aColorExternal = 1
        endif
    endif

And iVim works fine now.

I wonder what changes in the new version have broken the system support. I know the previous version of iVim didn't support system command, but, somehow, it handled them without hanging. 

Thank you, again, for porting Vim to the iPad. It has changed the way I work.

**Comment by terrychou** [comment]
Thanks for the following-up report and glad to know that you have already fixed the problem.

Yes, the main change in version 2.10 is the addition of support of external commands. By default, Apple disables completely the ability of starting new processes via system calls. Thanks to the project [ios_system](https://github.com/holzschu/ios_system), iVim adds the support, well, in a hacking way. 

Because of this, the piece of script in question had no problem before (the function `system` would always fail). After version 2.10, the function `system` will try to do its work. However, since it is not implemented in a genuine way, it cannot handle complex commands, like the `osascript -e ...` part and crashes. The problem is that the `has('mac')` should return `0` in iVim, I will fix that.

**Comment by terrychou** [comment]
`has("mac")` has been disabled in version 2.12.
